<?php

namespace S2WPImporter;

/**
 * Reads the `*.asset.php` manifests generated by the build
 * (@wordpress/dependency-extraction-webpack-plugin) in a way that never fatals.
 *
 * On PHP 8+, `include` of a missing file returns `false` and indexing it yields
 * `null`, which makes `array_merge()`/`wp_enqueue_script()` throw a TypeError.
 * This helper always returns a well-formed array so an unbuilt checkout or a
 * corrupted manifest degrades to sensible defaults instead of a white screen.
 */
class Assets
{
    /**
     * @param string             $relativePath        Manifest path relative to the plugin root.
     * @param array<int, string> $defaultDependencies Script handles used when the manifest is unavailable.
     * @return array{dependencies: array<int, string>, version: string}
     */
    public static function meta($relativePath, array $defaultDependencies = [])
    {
        $default = [
                'dependencies' => $defaultDependencies,
                'version' => S2WP_IMPORTER_VERSION,
        ];

        $file = S2WP_IMPORTER_DIR . ltrim($relativePath, '/\\');
        if (!is_file($file) || !is_readable($file)) {
            return $default;
        }

        $asset = include $file;
        if (!is_array($asset)) {
            return $default;
        }

        $dependencies = isset($asset['dependencies']) && is_array($asset['dependencies'])
                ? array_values(array_filter($asset['dependencies'], 'is_string'))
                : $default['dependencies'];

        $version = isset($asset['version']) && is_scalar($asset['version']) && '' !== (string) $asset['version']
                ? (string) $asset['version']
                : $default['version'];

        return [
                'dependencies' => $dependencies,
                'version' => $version,
        ];
    }
}
